version: "3.1" 
services:
  glm_test:
    image: wdwatkins/national_site_reach:v0.2
    build:
      context: .
    ports:
      - "8787:8787"
    environment:
      - ROOT=TRUE
      - PASSWORD=mypass

